language: java
sudo: required
services:
  - docker
jdk: oraclejdk8
install: 
  - "mvn package docker:build"
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker push cngroup/hakka-backend'
