language: java
sudo: required
services:
  - docker
jdk: oraclejdk8
script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"  
install: 
  - "mvn package docker:build"
  - "docker push cngroup/hakka-backend"
